version: '3'
volumes:
  postgres-data:
    driver: "local"
networks:
  proxy:
    external: true
  internal:
    external: false
services:
  database:
    image: postgres
    container_name: laravel-jwt-database
    environment:
      - "POSTGRES_DB=laravel"
      - "POSTGRES_USER=laravel"
      - "POSTGRES_PASSWORD=laravel"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  php:
    build: ./docker
    container_name: laravel-jwt-php
    volumes:
      - ./api:/api
    links:
      - database
    depends_on:
      - database
  api-laravel:
    image: nginx:latest
    container_name: laravel-jwt-nginx
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    links:
      - php
      - database
    depends_on:
      - php
    labels:
      - traefik.enable=true
      - traefik.backend=api-laravel
      - traefik.frontend.rule=Host:api-laravel.lucasmarques73.com.br
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - internal
      - proxy
  