version: '3'
volumes:
  postgres-data:
    driver: "local"
services:
  database:
    image: postgres
    container_name: laravel-jwt-database
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=laravel"
      - "POSTGRES_USER=laravel"
      - "POSTGRES_PASSWORD=laravel"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  php:
    build: ./docker
    container_name: laravel-jwt-php
    volumes:
      - ./api:/api
    depends_on:
      - database
  nginx:
    image: nginx:latest
    container_name: laravel-jwt-nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    links:
      - php
      - database
    depends_on:
      - php
  adminer:
    image: adminer
    container_name: laravel-jwt-adminer
    ports:
      - 8080:8080